# Generated by Django 4.1.5 on 2024-03-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=50)),
                ('userPic', models.CharField(max_length=150)),
                ('registerDate', models.DateField(auto_now_add=True)),
                ('userType', models.CharField(choices=[('Organizer', 'Organizer'), ('Attendee', 'Attendee')], max_length=50)),
            ],
        ),
    ]
