# Generated by Django 4.1.5 on 2024-03-25 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0003_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('registerId', models.AutoField(primary_key=True, serialize=False)),
                ('registrationDate', models.DateField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_app.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_app.user')),
            ],
        ),
    ]
